# Introduction to Numpy

## Functions

In [2]:
!pip install numpy

In [5]:
import numpy as np

## create array using numpy

arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [8]:
arr2 = np.array([1, 2, 3, 4, 5])
arr2.reshape(1, 5)
print(arr2.shape)

(5,)


In [10]:
arr2 = np.array([[1, 2, 3, 4, 5]])
print(arr2.shape)

(1, 5)


In [12]:
arr3 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]])
print(arr3)
print(arr3.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
(4, 5)


In [28]:
np.arange(1, 1001, 1).reshape(100, 10)

array([[   1,    2,    3,    4,    5,    6,    7,    8,    9,   10],
       [  11,   12,   13,   14,   15,   16,   17,   18,   19,   20],
       [  21,   22,   23,   24,   25,   26,   27,   28,   29,   30],
       [  31,   32,   33,   34,   35,   36,   37,   38,   39,   40],
       [  41,   42,   43,   44,   45,   46,   47,   48,   49,   50],
       [  51,   52,   53,   54,   55,   56,   57,   58,   59,   60],
       [  61,   62,   63,   64,   65,   66,   67,   68,   69,   70],
       [  71,   72,   73,   74,   75,   76,   77,   78,   79,   80],
       [  81,   82,   83,   84,   85,   86,   87,   88,   89,   90],
       [  91,   92,   93,   94,   95,   96,   97,   98,   99,  100],
       [ 101,  102,  103,  104,  105,  106,  107,  108,  109,  110],
       [ 111,  112,  113,  114,  115,  116,  117,  118,  119,  120],
       [ 121,  122,  123,  124,  125,  126,  127,  128,  129,  130],
       [ 131,  132,  133,  134,  135,  136,  137,  138,  139,  140],
       [ 141,  142,  143,  144,  1

In [30]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Attributes of numpy array

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", arr, "\n")
print("Shape: ", arr.shape)
print("No. of dimensions: ", arr.ndim)
print("Size (No. of elements): ", arr.size)
print("Datatype: ", arr.dtype)
print("Item size (in bytes): ", arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]] 

Shape:  (2, 3)
No. of dimensions:  2
Size (No. of elements):  6
Datatype:  int64
Item size (in bytes):  8


## Numpy Vectorised Operations

In [ ]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20, 30, 40, 50])

# Element-Wise Addition
print("Addition: ", arr1 + arr2)

# Element-Wise Subtraction
print("Subtraction: ", arr1 - arr2)

# Element-Wise Multiplication
print("Multiplication: ", arr1 * arr2)

# Element-Wise Division
print("Division: ", arr1 / arr2)

Addition:  [11 22 33 44 55]
Subtraction:  [ -9 -18 -27 -36 -45]
Multiplication:  [ 10  40  90 160 250]
Division:  [0.1 0.1 0.1 0.1 0.1]


## Universal Function

In [4]:
arr = np.array([2, 3, 4, 5, 6])

# square root
print(np.sqrt(arr))

# exponential 
print(np.exp(arr))

# sine
print(np.sin(arr))

# natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


## Array Slicing and Indexing

In [7]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("Array:\n", arr, "\n")

Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 



In [8]:
print(arr[0][2])

3


In [17]:
print(arr[1:, 2:], "\n")
print(arr[1:, 1:3], "\n")

[[ 7  8]
 [11 12]] 

[[ 6  7]
 [10 11]] 



In [4]:
# Modify array elements
arr[0, 0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [3]:
arr[1:] = 100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


### Statistical Concept

In [15]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(data)

# Mean
mean = np.mean(data)
print("Mean = ", mean)

# Median
median = np.median(data)
print("Median = ", median)

# Standard Deviation
std_div = np.std(data)
print("Standard Deviation = ", std_div)

# Variance
variance = np.var(data)
print("Variance = ", variance)

[ 1  2  3  4  5  6  7  8  9 10]
Mean =  5.5
Median =  5.5
Standard Deviation =  2.8722813232690143
Variance =  8.25


In [14]:
# Normalisation - to have a mean of 0 and standard deviation of 1

data = np.array([1, 2, 3, 4, 5])

# Calculate the mean and standard deviation 
mean = np.mean(data)
std_dev = np.std(data)
print("Data before Normalization: ", data, "\nMean = ", mean, "\tStandard Deviation = ", std_dev, "\n")

# Normalize the data
normalized_data = (data - mean) / std_dev
normalized_mean = np.mean(normalized_data)
normalized_std_dev = np.std(normalized_data)
print("Data after Normalization: ", normalized_data, "\nMean = ", normalized_mean, "\tStandard Deviation = ", normalized_std_dev, "\n")

Data before Normalization:  [1 2 3 4 5] 
Mean =  3.0 	Standard Deviation =  1.4142135623730951 

Data after Normalization:  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356] 
Mean =  0.0 	Standard Deviation =  0.9999999999999999 



### Logical Operation

In [18]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(data, "\n")

print(data > 5, "\n")
print(data[(data >= 5)], "\n")
print(data[(data >= 5) & (data <= 8)], "\n")

[ 1  2  3  4  5  6  7  8  9 10] 

[False False False False False  True  True  True  True  True] 

[ 5  6  7  8  9 10] 

[5 6 7 8] 

